POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "age": 30
}

###

GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/users/6a752aeb-7f54-4bc3-9bf1-32f85039d41f

###

PUT http://localhost:3000/api/users/6a752aeb-7f54-4bc3-9bf1-32f85039d41f
Content-Type: application/json

{
    "name": "Updated Name",
    "email": "updated.email@example.com",
    "age": 35
}

###

DELETE http://localhost:3000/api/users/b8a97e66-5702-439a-8e5d-a79229299eab

